server:
  port: 7001


eureka:
  instance:
    hostname:  localhost #www.eureka7001.com
  client:
    #false表示自己就是注册中心，不需要检索服务
    fetch-registry: false  #不注册自己
    register-with-eureka: false # 不检索自己
    service-url:
      #      defaultZone: http://www.eureka7002.com:7002/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   #http://www.eureka7001.com:7001/eureka/
#  server:
#    #关闭自我保护机制，保证不可用服务立即被踢出
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000
